FROM ghcr.io/ansible/ansible-devspaces:latest

USER 0

COPY --chown=0:0 entrypoint.sh /
COPY --chown=0:0 set-cgroups.sh /

RUN chmod +x /set-cgroups.sh ; \
    chmod +x /entrypoint.sh

USER 1000
ENTRYPOINT ["/entrypoint.sh"]
CMD [ "tail", "-f", "/dev/null" ]